env: local

# Переодичность чтения триггеров Zabbix
update_interval: 2s

# Настройки для подключения к MQTT брокеру
mqtt:
    address: tcp://localhost:1883
    client_id: smith-zabbix-mqtt

    # Если false, то логин и пароль игнорируются
    authorization: false
    login: 
    password: 

# Настройки для подключения к API Zabbix
zabbix:
    address: http://localhost:8080/api_jsonrpc.php
    token: 

    # Если указать группу, то будут запрашиваться только те триггеры,
    # в которых хосты принадлежат данной группе
    group: 

# Переопределение приоритетов Zabbix в приоритеты сервера подсветки "Хамелеон"
#
# Приритеты триггеров в Zabbix:
#   0: Не классифицировано
#   1: Информация
#   2: Предупреждение
#   3: Средняя
#   4: Высокая
#   5: Чрезвычайная
# Приоритеты сервера "Хамелеон":
#   2: Все хорошо (Синий цвет)
#   3: Внимание (Желтый цвет)
#   4: Авария (Красный цвет)
severity:
    0: 2
    1: 2
    2: 3
    3: 3
    4: 4
    5: 4

# Перечисление хостов Zabbix, за которыми нужно следить (Имя узла сети)
hosts:
    - Zabbix server # Сервер Zabbix 

# Настройки создания виртуального устройства в MQTT WirenBoard
# Создается топик "/device/имя_устройства/controls/перечисления_хостов"
mqtt_virtual_device: 

    # Имя используется для формирования топика устройства
    name: statusServers

    # Публиковать или нет общее количество активных триггеров Zabbix
    total_triggers: true

    # Публиковать или нет общий аптайм работы сервиса
    uptime: true
