env: local

# Переодичность чтения триггеров Zabbix
update_interval: 2s

# Настройки для подключения к MQTT брокеру
mqtt:
    address: tcp://localhost:1883
    client_id: smith-zabbix-mqtt

    # Если false, то логин и пароль игнорируются
    authorization: false
    login: 
    password: 

# Настройки для подключения к API Zabbix
zabbix:
    address: http://localhost:8080/api_jsonrpc.php
    token: 

    # Если указать группу, то будут запрашиваться только те триггеры,
    # в которых хосты принадлежат данной группе
    group: 

# Переопределение приоритетов Zabbix в приоритеты сервера подсветки "Хамелеон"
#
# Приритеты триггеров в Zabbix:
#   0: Не классифицировано
#   1: Информация
#   2: Предупреждение
#   3: Средняя
#   4: Высокая
#   5: Чрезвычайная
# Приоритеты сервера "Хамелеон":
#   2: Все хорошо (Синий цвет)
#   3: Внимание (Желтый цвет)
#   4: Авария (Красный цвет)
severity:
    0: 2
    1: 2
    2: 3
    3: 3
    4: 4
    5: 4

# Настройки публикации топиков в MQTT брокер
topics:

    # Топик, куда будет публиковаться общее кол-во активных триггеров в Zabbix
    total_triggers: 

    # Топик, куда будет публиковаться время аптайма работы сервиса
    uptime: 

    # Список серверов
    # Указываем для хоста топик для публикации приоритета триггера.
    # имя_хоста_в_Zabbix: топик_для_публикации
    servers:
        Zabbix server: /devices/statusServers/controls/Zabbix-server #Сервер 1